### PR TITLE
Added Display Token,Wallet balance in $ and zkSync Lite Activity

### PR DESCRIPTION
**Pull request by rayaanr**
Changes Made:
- Added Token Balance display in $
- Added Total Wallet Balance display
- Updated favicon to the ZKFlow logo

Xnip2023-06-05_13-49-26_cropped

And added the zkSync Lite activity for that respective address

https://github.com/ByFishh/zk-flow/assets/108685206/9eed1ca4-12f4-4aaa-99eb-e59fe2ded195

### CODE REVIEW

**Comment by ByFishh** [comment]
Very nice work, I will rework some smalls css things this night and we will merge

**Comment by rayaanr** [comment]
Cool.

In zkSync Lite, the activation date only works for addresses that have fewer than 100 txns. This is because I couldn't find a method to retrieve all the transactions (the API is limited to 100). Therefore, it is not possible to obtain the oldest transactions for those addresses.

**Comment by ByFishh** [comment]
Ok mate I will edit that. I will do a tweet this afternoon to announce the updates, do you want to be mentionned (twitter or github) ?

**Comment by rayaanr** [comment]
No need to mention me in the tweet. It's completely up to you. I'm just happy to help and contribute in any way I can. Feel free to proceed with the tweet as you see fit.

**Pull request merged**
